### PR TITLE
Proposals caps first

### LINKED ISSUE #248: Remove validate_caps_first for only MEL
La MEL is bothered by the fact that if the proposal doesn't start with a cap, it cannot be published. They would like for us to remove this validation ( `validate_caps_first`method in `decidim/decidim-core/app/validators/etiquette_validator.rb`)

Exemple of this validation here:
capture d ecran 2018-09-10 a 16 16 24

Problem is, if we do the modification at the decidim level, it will be removed for all the clients.
In my opinion I think this rule is quite useful as it significantly improves the readability of the proposal and is not too restrictive for the user. If he forgets to put a cap first, the message telling him to do so is straight-forward. Thus I do not think it's a good thing to remove this rule for all the clients.
If so, it should be documented in the MEL's changelog as @moustachu suggested it.

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :tophat: What? Why?
Capitalize title and body for the user is more friendly and avoid the frustration of getting your proposals rejected for a typo, or because you don't know it was mandatory.

#### :pushpin: Related Issues
- Fixes #248

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [x] Add tests

### :camera: Screenshots (optional)
image

### CODE REVIEW

**Comment by armandfardeau** [comment]
@moustachu Decidim-proposals tests seems broken, do you know how to make a proper concerns?

**Comment by moustachu** [comment]
@armandfardeau merge **to master** ??

**Comment by armandfardeau** [comment]
> @armandfardeau merge **to master** ??

-> Fixed

**Comment by armandfardeau** [comment]
@moustachu I just re-run tests : 
Failure/Error:
  describe ProposalForm do
    it_behaves_like "a proposal form"
  end

LoadError:
  Unable to autoload constant Decidim::Proposals::Admin::ProposalForm, expected /Users/armandfardeau/WWW/osp-decidim/decidim-proposals/app/forms/decidim/proposals/admin/proposal_form.rb to define it

**Pull request merged**
