### PR TITLE
Add the ability for an admin to contact a user directly

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :tophat: What? Why?

As suggested by Valentin and Virgille in a meeting, the process to contact a user from admin panel is not optimised. They have to copy/paste the user id in the conversation area to start a chat. 
**This is over !** 
Now the administrator can start a conversation directly from the back office with a user.

### :camera: Screenshots
image

#### :ghost: GIF
GIF

### CODE REVIEW

**Comment by armandfardeau** [comment]
@juliesimon @virgile-dev @moustachu 

Let's discuss that feature, is that something you find useful?

**Comment by virgile-dev** [comment]
Hey @armandfardeau 

Yep definitely useful from the admin perspective.
I'm thinking about the process here in general here : 
1. Propose functionnality on meta.decidim.org
2. After discussing it with decidim team, if we see some approval we start coding.
3. Write the functionnal test
4. Code the feature
5. Send the PR.

We can take a shortcut for this one but I think we can adopt something like that in the feature.

Here is my feedback on this feature : 
- The envelope should have the same grey as the action icons
- I think we should keep the regular flow as is when the user clicks on **<** to get back to all the conversations. What do you think ?
capture d ecran 2018-08-03 a 10 46 11

**Comment by juliesimon** [comment]
I agree with Virgile's feedback.

This feature is definitely useful but I also remember that this feature was part of a broader improvement of the "validation" panel. We said indeed that it would be nice that the columns can be "orderable", like in the proposals panel:
capture d ecran 2018-08-03 a 11 19 55

We were also saying that when administrating many proposals for a participatory budget, the admin needs to be able to contact the user to discuss his/her proposal. So it might be nice to add a "envelop" icon to contact the author of the proposal as an action (see capture above - red square).

Either we decide that it is better to do "major" improvements (here, "Improve admin to user communication") and so it needs further discussion, design etc. Or first merge Armand's dev and we'll discuss the rest later.

**Comment by armandfardeau** [comment]
Closing due to recent backport

**Pull request closed without merging**
