### PR TITLE
Fix progress meter when over 100%

### LINKED ISSUE #144: Progress meter exceeds container width where progress is over 100%
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong?
Progress meter exceeds container width where progress is over 100% 
* What did you expect should have happened?
Progress meter should not exceeds container width where progress is over 100% 
* What was the config you used?
0.12-stable on dev app

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
Chrome67
* ***Screenshot***:
image

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :tophat: What? Why?
Fix progress meter when over 100%

#### :pushpin: Related Issues
- Fixes #144 

### :camera: Screenshots (optional)
image

### CODE REVIEW

**Comment by juliesimon** [comment]
@armandfardeau test fonctionnel ok

**Comment by armandfardeau** [comment]
@juliesimon @moustachu As my PR is going to be merge in [Decidim/Decidim](https://github.com/decidim/decidim/pull/3952), I suggest that we closed this one and will redo a PR with the appropriate correction.

**Comment by juliesimon** [comment]
Woooohooooo 1st OSP's PR to Decidim 🍾 🎉 
Well done @armandfardeau !

**Comment by virgile-dev** [comment]
Well done !!!

**Pull request closed without merging**
