### PR TITLE
Fix proposal search

### PR DESCRIPTION
**Pull request by armandfardeau**
- [x] Fix proposal search
- [x] "Amendments" filter option appears even if amendments are not activated

### CODE REVIEW

**Comment by armandfardeau** [comment]
@Quentinchampenois Are you ready for review?

**Comment by Quentinchampenois** [comment]
Hi ! To me it's ready for review

**Comment by armandfardeau** [comment]
@Quentinchampenois Sounds great, would you mind to reintroduce the tests I've added?

https://github.com/OpenSourcePolitics/decidim/pull/872/commits/510aa91ab7b71365ad167df4abad1b5c2ba56113

**Comment by Quentinchampenois** [comment]
@armandfardeau of course it was a mistake !

**Pull request merged**
