### PR TITLE
Feature/admin proposals filter & search

### PR DESCRIPTION
**Pull request by moustachu**
#### :tophat: What? Why?

Implements #454 & #456 🎉 

#### :clipboard: Subtasks
- [ ] Add `CHANGELOG` entry
- [ ] Add documentation regarding the feature 
- [ ] Add tests

### :camera: Screenshots (optional)

capture d ecran 2019-02-07 a 10 51 39

### CODE REVIEW

**Comment by moustachu** [comment]
Don't worry about the merge conflicts : my feature branch was pulled from the last 0.16-stable so we are missing a few commits on our 0.16. 

If I update our 0.16-stable with the last changes, they should be updated and removed on this PR.

**Comment by moustachu** [comment]
@lu-hamani The branch was pushed because you can't give a try to the UX here : 
https://sandbox.steamroll.osp.cat/admin/participatory_processes/itaque-in/components/12/manage/proposals?locale=fr

⚠️ Columns are not displayed when the filter is selected !

**Comment by lu-hamani** [comment]
@moustachu 
> ⚠️ Columns are not displayed when the filter is selected !
I am not sure what you are referring to when you say "Columns"

Regarding the UX/UI, there is one thing that might cause a problem. There are no clear distinction between 2 categories or a category and its sub-categories when filtering.
screenshot 2019-02-07 at 11 44 43

For sure the latin doesn't help but still. What do you think ?

**Comment by lu-hamani** [comment]
@moustachu 
> Regarding the UX/UI, there is one thing that might cause a problem. There are no clear distinction between 2 categories or a category and its sub-categories when filtering.
> For sure the latin doesn't help but still. What do you think ?

For what it's worth, I just used Pauline as guinea pig and she didn't even notice there were 2 categories and subcategories in the category filter

**Comment by moustachu** [comment]
@lu-hamani Good point ! 

I wanted to add another level of menu for the sub category but : 
- we have to manage when the user want to select a category with child --> display submenu on hover and select category on click ?
- Categories and sub are always displayed this way on Decidim, so I choose to keep it consistent for the first release

Just in case you want to test this alternative, I do need ~1h to make the changes and push that on sandbox

**Comment by lu-hamani** [comment]
> @lu-hamani Good point !
> 
> I wanted to add another level of menu for the sub category but :
> 
> * we have to manage when the user want to select a category with child --> display submenu on hover and select category on click ?
> * Categories and sub are always displayed this way on Decidim, so I choose to keep it consistent for the first release
> 
> Just in case you want to test this alternative, I do need ~1h to make the changes and push that on sandbox

Let's go for a sub-menu first. I think will test it out with clients to settle the matter. We'll talk about it tomorrow during the technical meeting

**Pull request closed without merging**
