### PR TITLE
Processes search

### LINKED ISSUE #179: Ability to order processes in the back-office
Not urgent but a fix would be nice!

As noticed by a client, participatory processes seem randomly ordered (neither by date nor by alphabetical order) on the administration panel 
https://club.decidim.opensourcepolitics.eu/processes/new-components/f/95/proposals/208#proposal_208

An admin should be able to choose and display processes by date or alphabetical order.

Follow Barcelona decision : https://meta.decidim.org/processes/roadmap/f/122/proposals/13099

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :tophat: What? Why?
Ability to order processes in the back-office

#### :pushpin: Related Issues
- Fixes #179

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [x] Add tests

### :camera: Screenshots (optional)

GIF WEEEE

### CODE REVIEW

**Comment by armandfardeau** [comment]
@moustachu Could you give me a hint how to to refactor this to ensure a better future compatibility?

**Comment by moustachu** [comment]
@armandfardeau not sure if I have a useful hint on that subject. 
But if you copied / adapted the proposals search (admin) for the processes, it should be fine. 

⚠️ Just make sure that the "private space" are managed correctly (meaning >> hidden for admin user that ara not listed for a private process)

**Comment by armandfardeau** [comment]
I will add that condition to tests.

**Comment by armandfardeau** [comment]
@moustachu This should be done tomorrow morning as i found an unelegant but working way to test !

**Comment by armandfardeau** [comment]
@moustachu 100% tested ! I noticed that Proposals sorting is not test on admin side, should I add some tests? (Should be quick, it just a duplicate of theses ones)

**Review by lu-hamani — DISMISSED** [review]
Works fine. I wonder if the hover is self-explanatory so as to sort the processes though.

**Review by moustachu — APPROVED** [review]
Seems OK

@moustachu To be deployed on steamroll

**Pull request merged**
