### PR TITLE
Feature/views archive category

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [ ] If there's a new public field, add it to GraphQL API
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
Description

### CODE REVIEW

**Review by Quentinchampenois — APPROVED** [review]

**Review by paulinebessoles — CHANGES_REQUESTED** [review]
Thanks @armandfardeau ! 
I have just one feedback, could you reduce the "Archived" logo `max-width` from 100% to 30% and horizontally align the image at the center of the `archive-header`?

**Comment by armandfardeau** [comment]
> Thanks @armandfardeau !
> I have just one feedback, could you reduce the "Archived" logo `max-width` from 100% to 30% and horizontally align the image at the center of the `archive-header`?

For sure.

Capture d’écran 2021-05-03 à 18 57 53

**Comment by paulinebessoles** [comment]
Thanks! I'm waiting for the client feedback before merging.

**Comment by armandfardeau** [comment]
> Thanks! I'm waiting for the client feedback before merging.



> Thanks! I'm waiting for the client feedback before merging.

No, we should wait on the destination branch.

**Pull request merged**
