### PR TITLE
Backport/correct from email field smtp settings

### PR DESCRIPTION
**Pull request by Dynnammo**
#### :tophat: What? Why?
When changing fields in `System > Organization > <your-organization> > SMTP Settings` (`from_email` and `from_label`), it does not update.

What's the matter ?
There is three fields concerned by such issue : `from_email`, `from_label` and `from`
`from_email` stores the **bare bone** email of the system ie. `noreply@example.org`
`from_label` stores the **name** under which we should send mails. As instance : 'My organization'
The `from` attribute is there to make a concatenation of both. It is defined in `set_from` in `update_organization_form.rb`

What does this pull request is : 
- define correctly from field
- correct tests that comes along

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
Related PR : https://github.com/OpenSourcePolitics/decidim/pull/962

#### Testing
- Go to `System > Organizations`, edit your organization and change field `from email` and `from label`
- Open a `letter_opener` : http://localhost:3000/letter_opener`
- Simulate a lost password / a procedure that sends email
- check on `letter_opener` tab that the email hasn't changed

#### :clipboard: Checklist
:rotating_light: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] :question: **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [x] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [x] :heavy_check_mark: **DO** build locally before pushing.
- [x] :heavy_check_mark: **DO** make sure tests pass.
- [x] :heavy_check_mark: **DO** make sure any new changes are documented in `docs/`.
- [x] :heavy_check_mark: **DO** add and modify seeds if necessary.
- [x] :heavy_check_mark: **DO** add CHANGELOG upgrade notes if required.
- [x] :heavy_check_mark: **DO** add to GraphQL API if there are new public fields.
- [x] :heavy_check_mark: **DO** add link to MetaDecidim if it's a new feature.
- [x] :x:**AVOID** breaking the continuous integration build.
- [x] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
*Please add screenshots of the changes you're proposing*
Description

:hearts: Thank you!

### CODE REVIEW

**Comment by paulinebessoles** [comment]
Tested and approved by product! Thanks @Dynnammo 
Capture d’écran 2020-10-28 à 09 56 44

**Review by paulinebessoles — APPROVED** [review]
Tested and approved by product! Thanks @Dynnammo 
Capture d’écran 2020-10-28 à 09 56 44

**Comment by armandfardeau** [comment]
Hi @Dynnammo and thanks for your contribution.

If I understand well, this is a backport, may you link the original P.R. in the description?
I think we should wait for the original to be merged

**Review by armandfardeau — CHANGES_REQUESTED** [review]
Wait for BCN and fix CI

**Comment by Dynnammo** [comment]
I added the original PR link in the description. Here it is fyo : https://github.com/OpenSourcePolitics/decidim/pull/962
The assembly bug is a flaky, I should have said it also. Should I make a PR to fix it ?

**Pull request closed without merging**
