### PR TITLE
Voting rules on budget module

### PR DESCRIPTION
**Pull request by aitorlb**
#### :tophat: What? Why?
We have agreed on:
- Excluding sub-categories on "project per category" rule; cc @valentinchaput 
- Validating specific voting rules fields in `Decidim::Admin::ComponentForm` via JavaScript as validations are broken in this version of decidim; cc @moustachu 

#### :pushpin: Related Issues
- Related to [Voting rules on budget module #1](https://github.com/OpenSourcePolitics/dev/issues/1)

#### :clipboard: Subtasks
- [ ] Add `CHANGELOG` entry
- [x] Add tests

#### Front-end BEFORE
unnamed-min

#### Front-end AFTER
budgets-min

#### Admin voting rules fieldset
admin_voting_rules-min

#### Admin voting rules modal
admin_voting_rules_modal-min

### CODE REVIEW

**Comment by virgile-dev** [comment]
Hey @aitorlb 
Thanks for the PR !
This little html problem is blocking us for further testing (check capture below). Thanks in advance.
Capture d’écran 2019-08-19 à 16 37 59

**Comment by paulinebessoles** [comment]
Hi Aitor ! 

With @armandfardeau and @virgile-dev, we tested the voting rules and have a few comments : 

- We need to **add a condition to the validation modal** : the sum of "minimum projects to select per category" for all categories can't be superior to the total number of projects to select. 
image

- When the vote per category is displayed, a selected project belonging to a subcategory doesn't count in the vote per category. 
The **projects belonging to sub-categories should be taken into account in the projects of the main category**. 
image

- The **minimum number of selected projects must be of 1** and, the module should display an error message when updating the module. Right now, it saves the update but when I go in the user panel, there's a Server error in the Budget module.
image

**Comment by valentinchaput** [comment]
A quick follow-up on @paulinebessoles's message: 
Second bullet-point, we decided earlier with Aitor to focus on the selection per category only (and not the selection per sub-category) as we don't know how to display it correctly on the front-end. Our client's need is limited to selection per category.

**Comment by paulinebessoles** [comment]
I misspoke, I meant that even if the voting rule just take into account main categories, the projects belonging to subcategories should be computed with the selected projects per category. 

In the screenshot I posted above, we can see that the selected project "Bernard Barnes", belonging to a subcategory of "Et molestiae ratione [...]" category isn't taken into account in the computing of the votes.

**Comment by aitorlb** [comment]
Hi @paulinebessoles. Thanks for the feedback. Some things:

> We need to add a condition to the validation modal : the sum of "minimum projects to select per category" for all categories can't be superior to the total number of projects to select.

I'm not sure I understand what you're asking here, as this is already validated in the back-end. You mean that you want to modify the text of the back-end modal?

> The minimum number of selected projects must be of 1 and, the module should display an error message when updating the module. Right now, it saves the update but when I go in the user panel, there's a Server error in the Budget module.

As for the Server error, can you provide the logs?

**Comment by aitorlb** [comment]
> When the vote per category is displayed, a selected project belonging to a subcategory doesn't count in the vote per category.
The projects belonging to sub-categories should be taken into account in the projects of the main category.

As @valentinchaput said, we decided to focus on categories in this iteration. The main point I rised regarding subcategories is about **enforcing** and **displaying** these rules, as they would have to take precedence over (parent) category rules. It's not so much a coding problem as a product problem, because you would need to define it really well for it to work the way you want.

What you've asked is different, because it stays in the scope of what we agreed on, that is: only enforce and show (parent) category rules :+1: .

**Comment by virgile-dev** [comment]
Hi @aitorlb 
> We need to add a condition to the validation modal : the sum of "minimum projects to select per category" for all categories can't be superior to the total number of projects to select.

We've verified in our test that this is not enforced by the back end. If not in the validation modal I'm guessing the error message is displayed directly under the field ?

> The minimum number of selected projects must be of 1 and, the module should display an error message when updating the module. Right now, it saves the update but when I go in the user panel, there's a Server error in the Budget module.
If the total number to select is 0 then the feature doesn't work. But I guess this one is more for us as we coded this feature. You can concentrate on the one above.

**Comment by aitorlb** [comment]
Hi @virgile-dev,
> We've verified in our test that this is not enforced by the back end. 

 Right now, the sum of "minimum projects to select per category" cannot surpass the total number of projects for the component, as that is what I understood from the issue:

> Sum of minimums for all categories cannot me over total number of projects.

This validation works both for `vote_per_project` and `vote_per_budget`.

What you're asking is to add another condition so when `vote_per_project` is enabled the limit of the sum of "minimum projects to select per category"  is the value of `total_projects`. Correct?

**Comment by virgile-dev** [comment]
@aitorlb sorry for the confusion. You understood correctly.
The sum of the minimums per category can't be superior to total number of projects needed to be selected in order to cast a vote.

**Comment by aitorlb** [comment]
@virgile-dev, I've applied the requested changes. Can you test again and provide feedback?

**Comment by virgile-dev** [comment]
Hello @aitorlb, 
This seems to be working as intended. Congrats !
Only one last test is not passing, could you check ? 

Last things :
The voting rules confirmation modal is triggered for reasons that or not explained in the modal : 
- total project to select is < 1  --> can we add a field confirmation message in red like "can't be inferior to 1"
Capture d’écran 2019-08-28 à 17 25 57

I feel that the first part of the modal to validate rules is useless as you can't select both  Activate rule: "number of projects selected" // Activate rule: "minimum budget percentage" at the same time.

I suggest the following improvement : 
Capture d’écran 2019-08-28 à 17 46 07

**Comment by aitorlb** [comment]
Hi @virgile-dev,

We can modify the modal as much as you want but I cannot add field error messages as they work via component form validations, which are broken in your decidim version.

As for the failing test, I'm going to take a look with @isaacmg410; it seems like a conflict with decidim-dev versions.

**Comment by virgile-dev** [comment]
>We can modify the modal as much as you want but I cannot add field error messages as they work via component form validations, which are broken in your decidim version.
@aitorlb Let's modify the modal as I suggested. 

Ok for the form validation as its related to our version.

Thanks

**Pull request merged**
