### PR TITLE
Allow debates to be reported

### LINKED ISSUE #194: There is no moderation on the Debate feature
Quite an urgent issue we must submit to Barcelona!

As far as I remember, the Debate feature started as a clone of a former version of Proposals. Unfortunately, it is missing a lot of stuff: 
- you cannot edit a debate you created as a user (even for a short period of time as with proposals)
- you cannot flag a debate, neither as a user nor as an admin, and therefore you cannot moderate a debate, which presents a legal issue for our clients 
- you cannot delete a debate as an admin (the issue would be to be able to moderate it)

--
Less urgent is the fact that we do not have the tool to compare a new debate with the previous ones that are already published.

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :tophat: What? Why?
Debates are now reportable when unofficial.

#### :pushpin: Related Issues
- Fixes #194

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [x] Add tests

### :camera: Screenshots (optional)

image

### CODE REVIEW

**Comment by armandfardeau** [comment]
@moustachu May you have a look on my code ?  I'm adding some tests currently.

**Comment by juliesimon** [comment]
Tested locally, everthing works fine !

Only problem is, when a debate reported and then hidden, it still appears in the stats on the participatory process' show.

Here I have 3 debates because I moderated one:
capture d ecran 2018-09-03 a 12 10 29

But on the stats it says there are 4 debates:
capture d ecran 2018-09-03 a 12 10 41

Did not count how many debates there were in total in my seeded platform, but I'm pretty sure there should be the same problem on the homepage stats section:
capture d ecran 2018-09-03 a 12 12 36

@armandfardeau could you please make sure only the debates that are not hidden are showed in the stats ?

**Comment by armandfardeau** [comment]
@juliesimon Is that the same with processes? If not, I'm sure will do it.

**Comment by moustachu** [comment]
@armandfardeau Code seems OK to me

I do agree with @juliesimon : **moderated** debates should be left off the statistics. 
If it's not the case for proposals, then we should raise a bug on the master branch.

**Comment by armandfardeau** [comment]
@moustachu @juliesimon This can be reviewed and shipped. We both agreed to treat stats issue aside.

**Review by juliesimon — APPROVED** [review]
Everything's ok from a functional point of view !

**Review by moustachu — COMMENTED** [review]
👍

**Pull request merged**
