### PR TITLE
Fixing test suite on 0.12-stable

### PR DESCRIPTION
**Pull request by moustachu**
#### :tophat: What? Why?

Because we need some green light :vertical_traffic_light: on that CircleCI status block !!

The goal here is to repair the original test cover of Decidim **before** adding new tests for our custom features. 

Most of the time when reparing a test you need to ask yourself : 
- Is the failing behavior normal (according to our custom features) ? 
- Is it the behavior or the way the code is implemented ?
- Should we remove or edit the failing test

> most of these cases are present on that commit ;) --> https://github.com/OpenSourcePolitics/decidim/commit/14d130f9c52b73b9e37f0e1f2a3e4d8016b146de

#### :pushpin: Related Issues
- Related to : _all_
- Fixes : _everything_

#### :clipboard: Subtasks
- [x] fix all test for `build_test_app`
- [x] fix all test for `build_design_app`
- [x] fix all test for `decidim-accountability`
- [x] fix all test for `decidim-admin`
- [x] fix all test for `decidim-api`
- [x] fix all test for `decidim-assemblies`
- [x] fix all test for `decidim-blogs`
- [x] fix all test for `decidim-budgets`
- [x] fix all test for `decidim-comments`
- [x] fix all test for `decidim-consultations`
- [x] fix all test for `decidim-core`
- [x] fix all test for `decidim-debates`
- [x] fix all test for `decidim-dev`
- [x] fix all test for `decidim-generators`
- [x] fix all test for `decidim-initiatives`
- [x] fix all test for `decidim-meetings`
- [x] fix all test for `decidim-pages`
- [x] fix all test for `decidim-participatory_processes`
- [x] fix all test for `decidim-proposals`
- [x] fix all test for `decidim-sortitions`
- [x] fix all test for `decidim-surveys`
- [x] fix all test for `decidim-system`
- [x] fix all test for `decidim-verifications`
- [x] fix all test for `main`

- [x] What changed between in the test architecture between 0.12 and 0.14.0.dev (master) ? see #134

### CODE REVIEW

**Comment by moustachu** [comment]
**BTW ;)**

### This PR has been updated to `0.12.2` ✨

**Comment by moustachu** [comment]
Following @armandfardeau advice : 

### --> let's use [gitmoji](https://gitmoji.carloscuesta.me/) to qualify our commits ✨

**Comment by moustachu** [comment]
_just added the new subtask : _
> What changed between in the test architecture between 0.12 and 0.14.0.dev (master) ? see #134

**Comment by armandfardeau** [comment]
Is the `bundle exec rake test_all` command is failing from your side too @moustachu  @juliesimon ?

**Comment by armandfardeau** [comment]
@juliesimon @moustachu 

Here are the actual unused keys, you should know that's it possible to hard-writes them in case there are needed.

```
Failure/Error: expect(unused_keys).to be_empty, "#{unused_keys.inspect} are unused"

       en
         decidim
           admin
             actions
               new_consultation: New Vote {:path=>"decidim-consultations/config/locales/en.yml", :locale=>"en"}
               new_question: New question {:path=>"decidim-consultations/config/locales/en.yml", :locale=>"en"}
               new_response: New response {:path=>"decidim-consultations/config/locales/en.yml", :locale=>"en"}
               new_process: New consultation {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
               new_process_group: New consultation group {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
               new_process_step: New stage {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
               new_process_user_role: New consultation user {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
               new_assembly: New assembly {:path=>"decidim-assemblies/config/locales/en.yml", :locale=>"en"}
               new_initiative_type: New type of initiative {:path=>"decidim-initiatives/config/locales/en.yml", :locale=>"en"}
             menu
               managed_users: Utilisateurs représentés {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
           meetings
             admin
               invite_join_meeting_mailer
                 invite
                   decline: Refuse the invitation {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
               invites
                 index
                   filter
                     accepted: Accepted {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                     all: All {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                     rejected: Rejected {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                     sent: Sent {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   filter_by: Filter by {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   invite_attendee: Invite a participant {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   invites: Invites {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   search: Search {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
               registrations
                 form
                   invites: Invites {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
             models
               invite
                 fields
                   email: Email {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   name: name {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   sent_at: Sent to {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   status: Status {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                 status
                   accepted: Accepted (%{at}) {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   rejected: Rejeted (%{at}) {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                   sent: Sent {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
             registrations
               decline_invitation
                 invalid: A problem occurred when the invitation was refused. {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
                 success: You successfully declined the invitation. {:path=>"decidim-meetings/config/locales/en.yml", :locale=>"en"}
           participatory_processes
             participatory_processes
               filters
                 counters
                   active: {"one"=>"1 active consultation", "other"=>"%{count} active consultations"} {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   all: {"one"=>"1 consultation", "other"=>"%{count} consultations"} {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   past: {"one"=>"1 past consultation", "other"=>"%{count} past consultations"} {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   upcoming: {"one"=>"1 concertation to come", "other"=>"%{count} upcoming consultations"} {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                 explanations
                   no_active: No active consultation {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   no_active_nor_upcoming: No active or upcoming consultations {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   no_active_nor_upcoming_callout: There are no active or upcoming consultations. Here is a list of past consultations. {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                 names
                   active: Active {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   all: All {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   past: Past {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                   upcoming: Upcoming {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
                 see: See {:path=>"decidim-participatory_processes/config/locales/en.yml", :locale=>"en"}
           account
             data_portability_export
               file_no_exists: The file does not exist {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               invalid_token: The token provided is invalid. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               no_token: No tokens provided {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               notice: Your export is currently in progress. You will receive an email when it is full. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           authorization_modals
             show
               expired
                 authorize: Allow again with "%{authorization}" {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 explanation: Your authorization has expired. To perform this action, you must renew your authorization with "%{authorization}". {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 title: Authorization expired {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               incomplete
                 cancel: Cancel {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 explanation: Even if you are currently authorized with "%{authorization}", we need to reauthorize you because we don't have the following data:'' {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 invalid_field: %{field} {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 reauthorize: Re-authorize {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 title: Please authorize again {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               missing
                 authorize: Allow with "%{authorization}". {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 explanation: To perform this action, you must be allowed with"%{authorization}". {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 title: Authorization required {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               pending
                 explanation: To perform this action, you must be authorized with "%{authorization}", but your authorization is still being validated. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 resume: Check your authorization progress "%{authorization}" {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 title: The authorization is still being validated {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               unauthorized
                 explanation: Sorry, you cannot perform this action because some of your authorization data does not match. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 invalid_field: %{field} valule %{value} is invalid. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 ok: All right {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
                 title: Not allowed {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           data_portability
             export
               ready: Ready {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
             show
               download_data: Download data {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               download_data_description: A file with all information associated with the account will be sent to <strong>%{user_email}</strong> {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               request_data: Request data {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           devise
             shared
               newsletter_modal
                 buttons
                   close_modal: Close window {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           export_mailer
             data_portability_export
               click_button: Click on the following button to download your data. The file will be available until %{date}. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               download: Download {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           forms
             navbar_links
               create
                 error: There was an error when creating this link. {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 success: Link created successfully {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
               destroy
                 success: Link successfully destroyed {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
               edit
                 title: Edit navbar link {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 update: Update {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
               form
                 link: Link {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 new_tab: Open in a new tab {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 same_tab: Open in the same tab {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 title: Title {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 weight: Weight {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
               new
                 create: Create {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 title: New navbar link {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
               no_links: No links created {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
               update
                 error: There was an error when updating this link. {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                 success: Link updated successfully {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
           invitations
             create
               error: There was a problem inviting your friends over {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               error_empty_form: Please enter at least one email address {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               success: We sent the invitations to your friends! {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
             index
               customize_message: Customize the invitation message {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               friend_email: Your friend's email address #%{index} {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               invitations_subtitle: Tell your friends about this site {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               invitations_title: Do you think more voices should be heard in %{organization_name}? {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               invite: Invite {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               visit_your_profile: Consult your profile {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           newsletters_opt_in
             unathorized: Sorry, this link is no longer available {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
             update
               error: Sorry, a problem occurred. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               success: Newsletter settings successfully updated {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           newsletters_opt_in_mailer
             notify
               body_1: The processing and protection of personal data is becoming increasingly important to us all. With the new General Data Protection Regulation (GDR) of 25 May 2018, individuals have better control over their personal data. For this reason, we need your consent to continue sending you relevant information about %{organization_name} activities. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               body_2: How can you give us your consent? Simply click on the following button: {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               body_3: With your consent, you will be able to continue to receive information about the platform's services. If, on the contrary, we do not receive a positive confirmation from you, we will stop sending you messages. If you confirm that you wish to stay informed, you will always have the option to cancel this choice at a later date. {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               button: Yes, I want to continue to receive relevant information {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               greetings: Salutations,<br/>%{nom_de_l'organisation}<br/><a href="%{organization_url}">%{organization_url}</a>a>a {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               hello: Good morning, {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
               subject: Do you want to continue to receive relevant information about %{organization_name}? {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           pages
             terms_and_conditions
               refuse
                 modal_close: Close window {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           moderations
             models
               moderation
                 fields
                   date: Date {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                   status: Status {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
                   type: Type {:path=>"decidim-admin/config/locales/en.yml", :locale=>"en"}
           proposals
             admin
               shared
                 info_proposal
                   proposal_votes_weight: Votes count {:path=>"decidim-proposals/config/locales/en.yml", :locale=>"en"}
             models
               proposal
                 fields
                   published_at: Publiée à {:path=>"decidim-proposals/config/locales/en.yml", :locale=>"en"}
             proposals
               vote_weight
                 count: {"one"=>"VOTE", "other"=>"VOTES"} {:path=>"decidim-proposals/config/locales/en.yml", :locale=>"en"}
                 neutral: Neutral {:path=>"decidim-proposals/config/locales/en.yml", :locale=>"en"}
         layouts
           decidim
             user_menu
               invite_friends: Invite friends {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
             user_profile
               my_data: My data {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
         password_validator
           domain_included_in_password: is too similar to the domain name of this platform {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           email_included_in_password: is too similar to your email {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           fallback: is not valid {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           name_included_in_password: is too similar to your name {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           not_enough_unique_characters: does not have enough unique characters {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           password_not_allowed: is not allowed {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           password_too_common: is too common {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           password_too_long: is too long {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"}
           password_too_short: is too short {:path=>"decidim-core/config/locales/en.yml", :locale=>"en"} are unused
     # ./spec/i18n_spec.rb:20:in `block (2 levels) in <top (required)>'

Finished in 34.17 seconds (files took 6.06 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/i18n_spec.rb:19 # I18n sanity does not have unused keys
```

**Pull request merged**
