### PR TITLE
feature/end-of-mandate-archive

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [ ] If there's a new public field, add it to GraphQL API
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
Description

### CODE REVIEW

**Review by paulinebessoles — APPROVED** [review]
Tested and approved by product! 🥳

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]
Hi, nice work ! 

Can you add the missing french translations ? 
I've encountered a zsh error when trying to run the task, have you ever encountered this error ? I think it is probably related to my environment

**Comment by paulinebessoles** [comment]
Hi @Quentinchampenois, I'll add the french translations in the morning 😊
No problem to run the task on my side

**Review by Quentinchampenois — APPROVED** [review]

**Comment by paulinebessoles** [comment]
@Quentinchampenois could you resolve conflicting files?
I think its related with the https://github.com/OpenSourcePolitics/decidim/pull/1123 feature

**Pull request merged**
