### PR TITLE
Set signature_end_date to current date for classified initiatives

### PR DESCRIPTION
**Pull request by Quentinchampenois**
#### :tophat: What? Why?

When an admin answers to an initiative, or update an answer, and choose the "classified" state, the `signature_end_date` is automatically set to current date.

#### :clipboard: Subtasks
- [x] Add javascript
- [x] Add tests
- [x] Rubocop linting

### CODE REVIEW

**Comment by paulinebessoles** [comment]
Thanks @Quentinchampenois !
Great work ;) 

I just have a feedback about the moment when the "end of signature collection period" is set on today.
The idea of this feature was that as soon as the admin set the "state" drop-down field on Classified, the end of signature collection date picker is set on today. 

Screenshot_2020-09-10 Lang-Stamm


Now, the behavior is the following : when I select "classified", the end of signature date picker doesn't change on the form, and I have to click on "update" to make the end of end of signature collection date 'today'. 
This behavior is good but the automatic set of end of signature date should be made earlier when filling the form.

**Comment by Quentinchampenois** [comment]
> Thanks @Quentinchampenois !
> Great work ;)
> 
> I just have a feedback about the moment when the "end of signature collection period" is set on today.
> The idea of this feature was that as soon as the admin set the "state" drop-down field on Classified, the end of signature collection date picker is set on today.
> 
> Screenshot_2020-09-10 Lang-Stamm
> 
> Now, the behavior is the following : when I select "classified", the end of signature date picker doesn't change on the form, and I have to click on "update" to make the end of end of signature collection date 'today'.
> This behavior is good but the automatic set of end of signature date should be made earlier when filling the form.

Hi @paulinebessoles,

Thank you for your feedback ! 
If the `signature_end_date` is set to current date when admin choose the classified state, the `signature_end_date` field has to be locked or admin can change the `signature_end_date` if he / she wants ?

**Comment by paulinebessoles** [comment]
> If the `signature_end_date` is set to current date when admin choose the classified state, the `signature_end_date` field has to be locked or admin can change the `signature_end_date` if he / she wants ?

Admin can still change the 'signature_end_date` if he / she wants! 
Good luck with JS 😉

**Comment by Quentinchampenois** [comment]
It should be better now @paulinebessoles !

**Review by moustachu — APPROVED** [review]

**Pull request merged**
